pipeline {

    agent any



    environment {

        DOCKER_IMAGE = "yourdockerhub/app"

        DOCKER_TAG = "${BUILD_NUMBER}"

    }



    stages {



        stage('Checkout') {

            steps {

                git branch: 'main',

                    url: 'https://github.com/yourrepo/app.git'

            }

        }



        stage('Build') {

            steps {

                sh 'docker build -t $DOCKER_IMAGE:$DOCKER_TAG .'

            }

        }



        stage('Deploy to Kubernetes') {

            steps {

                withCredentials([file(credentialsId: 'kubeconfig-prod', variable: 'KUBECONFIG')]) {

                    sh '''

                    kubectl get nodes

                    kubectl apply -f k8s/prod/

                    '''

                }

            }

        }

    }

}
